import Navbar from "@/components/navbar";
import Head from "next/head";
import React from "react";

const Component = ({ children, title }) => {
    return (
        <>
            <Head>
                <title>{`Jagres - ${title}`}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className=" bg-[#eeeeee] dark:bg-[#1f2937] ">{children}</div>
        </>
    );
};

export default Component;
